#!/usr/bin/env sh
set -eu

if [ -f ".env" ]; then
  echo ".env ja existe. Nada foi alterado."
  exit 0
fi

secret() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 48
  else
    tr -dc 'A-Za-z0-9' </dev/urandom | head -c 96
  fi
}

POSTGRES_PASSWORD_VALUE="$(secret)"
JWT_SECRET_VALUE="$(secret)"

cat > .env <<EOF
POSTGRES_DB=sgqherbamed
POSTGRES_USER=sgqherbamed
POSTGRES_PASSWORD=${POSTGRES_PASSWORD_VALUE}

JWT_SECRET=${JWT_SECRET_VALUE}
INITIAL_ADMIN_EMAIL=admin
INITIAL_ADMIN_PASSWORD=Herba@123
INITIAL_ADMIN_NAME=Administrador SGQ

ANTHROPIC_API_KEY=

FILE_UPLOAD_MAX_BYTES=15728640
BACKUP_INTERVAL_SECONDS=86400
BACKUP_RETENTION_DAYS=30

ARECO_SYNC_ENABLED=true
ARECO_SYNC_INTERVAL_MS=180000
ARECO_RECEBIMENTOS_LIMIT=1000
ARECO_RECEBIMENTOS_DAYS=30
ARECO_FORNECEDORES_LIMIT=5000
ARECO_FORNECEDORES_YEARS=5
ARECO_SQLSERVER_HOST=10.0.242.230
ARECO_SQLSERVER_PORT=5327
ARECO_SQLSERVER_DATABASE=VSatHerbamed
ARECO_SQLSERVER_USER=fabiano.alves
ARECO_SQLSERVER_PASSWORD=${ARECO_SQLSERVER_PASSWORD:-}

ARECO_RECEBIMENTOS_QUERY=
ARECO_MATERIAIS_QUERY=
ARECO_MATERIAIS_LIMIT=0
EOF

chmod 600 .env 2>/dev/null || true

echo ".env criado com POSTGRES_PASSWORD e JWT_SECRET fortes."
if [ -z "${ARECO_SQLSERVER_PASSWORD:-}" ]; then
  echo "Aviso: ARECO_SQLSERVER_PASSWORD ficou vazio. Preencha no .env para ativar a sincronizacao com o Areco."
fi
